#!/usr/bin/env bash
# Generated by coding-agents installer for {{AGENT_DISPLAY_NAME}}.
# Apptainer cwd-only sandbox wrapper. MVP scope — see docs/v2-deferred.md.
set -euo pipefail
umask 077

AGENT_NAME="{{AGENT_KEY}}"
AGENT_BINARY="{{AGENT_BINARY}}"

# --- Precondition: SLURM job ---
if [ -z "${SLURM_JOB_ID:-}" ]; then
  echo "agent-${AGENT_NAME}: refusing to run on submit node (SLURM_JOB_ID unset)." >&2
  echo "  Try: srun --account=compgen --time=08:00:00 --mem=5G --gres=tmpspace:5G \\" >&2
  echo "       --cpus-per-task=2 --job-name=${AGENT_NAME}_managed_de_ridder_lab \\" >&2
  echo "       --export=PATH,VIRTUAL_ENV,CONDA_PREFIX,CONDA_DEFAULT_ENV,LD_LIBRARY_PATH \\" >&2
  echo "       --pty bash" >&2
  exit 3
fi

# --- Job-name convention: <agent>_managed_de_ridder_lab (best effort) ---
# Lab convention so anything started via this installer is identifiable
# in `squeue` / accounting. Rename idempotently if the user forgot the
# --job-name flag at srun/sbatch time. scontrol may not be allowed for
# every user — tolerate failure silently.
WANTED_JOB_NAME="${AGENT_NAME}_managed_de_ridder_lab"
if [ "${SLURM_JOB_NAME:-}" != "$WANTED_JOB_NAME" ]; then
  if command -v scontrol >/dev/null 2>&1; then
    scontrol update jobid="$SLURM_JOB_ID" jobname="$WANTED_JOB_NAME" >/dev/null 2>&1 || true
  fi
fi

# --- Precondition: SIF readable ---
SIF="${AGENT_SIF:-{{DEFAULT_SIF_PATH}}}"
SIF_RESOLVED=$(readlink -e "$SIF" 2>/dev/null || true)
if [ -z "$SIF_RESOLVED" ] || [ ! -r "$SIF_RESOLVED" ]; then
  echo "agent-${AGENT_NAME}: SIF unreadable at $SIF (resolved: ${SIF_RESOLVED:-<broken>})." >&2
  echo "  Ask lab admin to build and copy the SIF to /hpc/compgen/users/shared/agent/." >&2
  exit 5
fi

# --- Precondition: cwd writable ---
if [ ! -w "$PWD" ]; then
  echo "agent-${AGENT_NAME}: cwd not writable: $PWD" >&2
  exit 7
fi

# --- Precondition: lab cwd policy (de Ridder lab convention) ---
#
# Refuse to run from places where running an agent is almost always a
# mistake: shared lab infrastructure (read-only by convention), or the
# bare `projects/` / `projects/<project>/` roots (work belongs in a
# subdir, typically `analysis/$USER/`).
#
# Soft-warn if $PWD doesn't contain $USER as a path component — lab
# convention is everyone works under their own analysis dir, e.g.
# /hpc/compgen/projects/<project>/<subproject>/analysis/$USER/. The
# warning is non-fatal so users with project-shared workspaces (CI
# containers, automation) aren't blocked.
case "$PWD" in
  /hpc/compgen/users/shared|/hpc/compgen/users/shared/*)
    echo "agent-${AGENT_NAME}: refusing to run from '$PWD' — /hpc/compgen/users/shared/* is shared lab infrastructure (the SIF lives here), not a user workspace." >&2
    echo "  Cd into your own analysis dir (e.g. /hpc/compgen/projects/<project>/<subproject>/analysis/${USER:-\$USER}/) and retry." >&2
    exit 12
    ;;
  /hpc/compgen/projects|/hpc/compgen/projects/)
    echo "agent-${AGENT_NAME}: refusing to run from the bare /hpc/compgen/projects root." >&2
    echo "  Cd into a specific project subdir (e.g. /hpc/compgen/projects/<project>/<subproject>/analysis/${USER:-\$USER}/) and retry." >&2
    exit 12
    ;;
  /hpc/compgen/projects/*)
    # Require at least one subdir under /hpc/compgen/projects/<project>/.
    # Path /hpc/compgen/projects/cool_project decomposes to 5 IFS=/ parts
    # ('', 'hpc', 'compgen', 'projects', 'cool_project'); we want ≥ 6.
    IFS='/' read -ra _PWD_PARTS <<< "$PWD"
    if [ "${#_PWD_PARTS[@]}" -lt 6 ]; then
      echo "agent-${AGENT_NAME}: refusing to run from a project root '$PWD' — work belongs in a subdir under the project." >&2
      echo "  Cd into a subdir (e.g. analysis/${USER:-\$USER}/) and retry." >&2
      exit 12
    fi
    unset _PWD_PARTS
    ;;
esac

# Soft warning: cwd doesn't contain $USER as a path component. Skipped
# silently if $USER itself is unset (CI containers, sandboxed shells).
# We sandwich $PWD with extra slashes so the glob matches a full path
# component, not a substring (avoids matching "dstoker" inside "dstokers").
if [ -n "${USER:-}" ]; then
  case "/$PWD/" in
    */"$USER"/*) ;;  # OK: $USER appears as a full path component
    *)
      echo "agent-${AGENT_NAME}: warning: cwd '$PWD' has no path component '$USER'." >&2
      echo "  Lab convention: work in your own subdir, e.g. /hpc/compgen/projects/<project>/<subproject>/analysis/$USER/. Continuing anyway." >&2
      ;;
  esac
fi

# --- Precondition: $PWD is shape-safe (security §3.1) ---
# Synthesis §3.1 / Sprint 1 Task 1.1: a hostile cwd path containing `"`,
# control characters, or newlines can forge audit-log entries via
# printf interpolation. Refuse the invocation up-front. Common cwds are
# all-printable POSIX paths; rejecting these characters is no false-
# positive risk. Multi-tenant users will hit oddly-named cwds eventually.
case "$PWD" in
  *[[:cntrl:]]*|*\"*|*$'\n'*|*$'\r'*)
    echo "agent-${AGENT_NAME}: refusing to run from a cwd containing control characters, double-quote, or newlines: $PWD" >&2
    echo "  This is almost always either a typo or an attack on the audit log. Move to a sane cwd and retry." >&2
    exit 6
    ;;
esac

# --- Precondition: jq is on host PATH (security §3.1) ---
# The audit-log JSONL build below relies on jq's escape semantics for
# every interpolated value (cwd, slurm job id, sif sha, argv). The
# previous fallback that hand-rolled JSON via printf is unsafe, so jq
# is now a hard requirement on the host. (jq is already present in the
# SIF for in-sandbox use.)
if ! command -v jq >/dev/null 2>&1; then
  echo "agent-${AGENT_NAME}: jq not in host PATH — required for safe audit-log JSON encoding." >&2
  echo "  Install jq (most clusters have it as a module: `module load jq`) and retry." >&2
  exit 10
fi

# --- Precondition: $TMPDIR (SLURM tmpspace expected) ---
if [ -z "${TMPDIR:-}" ] || [ ! -d "$TMPDIR" ]; then
  echo "agent-${AGENT_NAME}: \$TMPDIR is unset or missing — request --gres=tmpspace:5G in your srun." >&2
  exit 8
fi

# --- Canonicalize HOME ---
# SLURM can strip HOME from the env on some configurations even when it's
# in --export; downstream code (~/.claude/.credentials.json check, the
# pyvenv.cfg allowlist that resolves $HOME paths) needs HOME to be set
# under `set -u`. Look it up from passwd if missing.
if [ -z "${HOME:-}" ]; then
  if command -v getent >/dev/null 2>&1; then
    HOME=$(getent passwd "${USER:-$(id -un)}" | cut -d: -f6)
  fi
  if [ -z "${HOME:-}" ]; then
    echo "agent-${AGENT_NAME}: cannot determine \$HOME — pass it via srun --export." >&2
    exit 9
  fi
  export HOME
fi

# --- conda/venv carrying ($:ro per security H4; pyvenv.cfg canonicalized per H3) ---
ENV_BINDS=()
if [ -n "${VIRTUAL_ENV:-}" ]; then
  export APPTAINERENV_VIRTUAL_ENV="$VIRTUAL_ENV"
  if [ -f "$VIRTUAL_ENV/pyvenv.cfg" ]; then
    VENV_HOME=$(awk -F' *= *' '/^home/{print $2; exit}' "$VIRTUAL_ENV/pyvenv.cfg")
    if [ -n "$VENV_HOME" ]; then
      VENV_HOME_REAL=$(realpath -e "$VENV_HOME" 2>/dev/null || true)
      if [ -n "$VENV_HOME_REAL" ] && [[ "$VENV_HOME_REAL" != "$PWD"* ]]; then
        # Allowlist for pyvenv.cfg `home =` paths. We bind these read-only
        # into the sandbox so Python inside the venv can find its own
        # toolchain. Covers system Python, RHEL EPEL, Bright Cluster
        # modules, uv-managed Pythons (default install path is under
        # ~/.local/share/uv/python/…), conda installs in HOME, and pyenv.
        case "$VENV_HOME_REAL" in
          /opt/python/*|/usr/*|/cm/shared/apps/python/*) ;;
          "$HOME"/.local/share/uv/python/*) ;;
          "$HOME"/.local/uv/*) ;;
          "$HOME"/miniconda3/*|"$HOME"/miniconda/*) ;;
          "$HOME"/anaconda3/*|"$HOME"/anaconda/*) ;;
          "$HOME"/.pyenv/versions/*) ;;
          *)
            if [ -n "${CONDA_PREFIX:-}" ] && [[ "$VENV_HOME_REAL" == "$CONDA_PREFIX"* ]]; then
              :
            else
              echo "agent-${AGENT_NAME}: pyvenv.cfg home '$VENV_HOME_REAL' not in allowlist; ignoring." >&2
              VENV_HOME_REAL=""
            fi ;;
        esac
        if [ -n "$VENV_HOME_REAL" ]; then
          ENV_BINDS+=( --bind "$VENV_HOME_REAL:$VENV_HOME_REAL:ro" )
        fi
      fi
    fi
  fi
  export APPTAINERENV_PREPEND_PATH="$VIRTUAL_ENV/bin"
fi
if [ -n "${CONDA_PREFIX:-}" ]; then
  export APPTAINERENV_CONDA_PREFIX="$CONDA_PREFIX"
  export APPTAINERENV_CONDA_DEFAULT_ENV="${CONDA_DEFAULT_ENV:-}"
  CONDA_BASE="${CONDA_PREFIX%/envs/*}"
  [ "$CONDA_BASE" = "$CONDA_PREFIX" ] && CONDA_BASE="$CONDA_PREFIX"
  CONDA_BASE_REAL=$(realpath -e "$CONDA_BASE" 2>/dev/null || true)
  if [ -n "$CONDA_BASE_REAL" ] && [[ "$CONDA_BASE_REAL" != "$PWD"* ]]; then
    ENV_BINDS+=( --bind "$CONDA_BASE_REAL:$CONDA_BASE_REAL:ro" )
  fi
  if [ -z "${VIRTUAL_ENV:-}" ]; then
    export APPTAINERENV_PREPEND_PATH="$CONDA_PREFIX/bin"
  fi
fi
[ -n "${LD_LIBRARY_PATH:-}" ] && export APPTAINERENV_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"

# --- Per-provider API key passthrough from $AGENT_SECRETS_DIR (security M5) ---
#
# Two mechanisms, both load into the sandbox via apptainer's APPTAINERENV_*
# convention:
#
# 1. Single-value credential files — one secret per file. The file's name
#    (uppercased) becomes the env var name. We look for these patterns:
#       *_api_key         → <NAME>_API_KEY        (most providers)
#       *_token           → <NAME>_TOKEN          (HF, GitHub, Anthropic OAuth)
#       *_endpoint        → <NAME>_ENDPOINT       (Azure OpenAI, etc.)
#       *_base_url        → <NAME>_BASE_URL       (Azure OpenAI base URL)
#       *_project         → <NAME>_PROJECT        (GCP)
#       *_location        → <NAME>_LOCATION       (GCP region)
#       *_resource_name   → <NAME>_RESOURCE_NAME  (Azure)
#
#    Drop the file in $AGENT_SECRETS_DIR with mode 0600. Examples:
#       openrouter_api_key, anthropic_api_key, openai_api_key,
#       gemini_api_key, groq_api_key, deepseek_api_key, mistral_api_key,
#       xai_api_key, cohere_api_key, fireworks_api_key, perplexity_api_key,
#       cerebras_api_key, opencode_api_key, kimi_api_key, zai_api_key,
#       minimax_api_key, ai_gateway_api_key, copilot_github_token,
#       gh_token, github_token, hf_token, anthropic_oauth_token,
#       azure_openai_api_key, azure_openai_endpoint, azure_openai_base_url,
#       google_cloud_api_key
#
# 2. provider.env — KEY=VALUE pairs, one per line, # for comments. Use
#    this for multi-variable configs that don't fit the patterns above
#    (Azure resource names, GCP project IDs, custom base URLs, …).
#       AZURE_OPENAI_RESOURCE_NAME=mycompany-openai
#       GOOGLE_CLOUD_PROJECT=my-project-123
#       GOOGLE_CLOUD_LOCATION=us-central1
# Synthesis §3.2 / Sprint 1 Task 1.1: the previous parser stripped
# whitespace from key, accepted any KEY=VALUE, and exported it as
# APPTAINERENV_${KEY}. Apptainer's --containall filters the host LD_*
# / SINGULARITY_* family but does NOT filter PATH, PYTHONPATH,
# PYTHONSTARTUP, NODE_OPTIONS, BASH_ENV, PROMPT_COMMAND. A hostile
# provider.env could land arbitrary code execution inside the sandbox
# at agent startup, before any deny-rule hook fires.
#
# Defence: every KEY must (a) match the conservative regex
# ^[A-Z][A-Z0-9_]{0,63}$, AND (b) NOT match the poisonous-name pattern
# below. Same rules apply to filename-derived names from the *_api_key
# glob.
_is_poisonous_env_name() {
  case "$1" in
    PATH|HOME|USER|IFS|ENV|BASH_ENV|PS1|PS2|PS4|PROMPT_COMMAND)
      return 0 ;;
    LD_*|LIBPATH|PYTHON*|NODE_*|RUBY*|PERL*|JAVA_*)
      return 0 ;;
    APPTAINERENV_*|SINGULARITY_*|SINGULARITYENV_*)
      return 0 ;;
  esac
  return 1
}

_is_valid_env_name() {
  case "$1" in
    [A-Z]) return 0 ;;  # single uppercase letter
  esac
  # ^[A-Z][A-Z0-9_]{0,63}$
  [[ "$1" =~ ^[A-Z][A-Z0-9_]{0,63}$ ]]
}

if [ -n "${AGENT_SECRETS_DIR:-}" ] && [ -d "$AGENT_SECRETS_DIR" ]; then
  shopt -s nullglob
  for keyfile in \
      "$AGENT_SECRETS_DIR"/*_api_key \
      "$AGENT_SECRETS_DIR"/*_token \
      "$AGENT_SECRETS_DIR"/*_endpoint \
      "$AGENT_SECRETS_DIR"/*_base_url \
      "$AGENT_SECRETS_DIR"/*_project \
      "$AGENT_SECRETS_DIR"/*_location \
      "$AGENT_SECRETS_DIR"/*_resource_name; do
    [ -r "$keyfile" ] || continue
    name=$(basename "$keyfile")
    var_name=$(echo "$name" | tr '[:lower:]-' '[:upper:]_')
    if ! _is_valid_env_name "$var_name" || _is_poisonous_env_name "$var_name"; then
      echo "agent-${AGENT_NAME}: refusing env passthrough for filename '$name' → '$var_name' (poisonous or malformed); skipping." >&2
      continue
    fi
    value=$(<"$keyfile")
    # Strip trailing newline so string-equality checks aren't tripped up.
    export "APPTAINERENV_${var_name}=${value%$'\n'}"
  done
  shopt -u nullglob

  if [ -r "$AGENT_SECRETS_DIR/provider.env" ]; then
    while IFS='=' read -r key val; do
      key="${key#"${key%%[![:space:]]*}"}"   # trim leading whitespace
      key="${key%"${key##*[![:space:]]}"}"   # trim trailing whitespace
      [ -z "$key" ] && continue
      case "$key" in \#*) continue ;; esac
      if ! _is_valid_env_name "$key" || _is_poisonous_env_name "$key"; then
        echo "agent-${AGENT_NAME}: refusing provider.env entry '$key' (must match ^[A-Z][A-Z0-9_]{0,63}\$ and not be a poisonous name); skipping." >&2
        continue
      fi
      val="${val%$'\n'}"
      val="${val#\"}"; val="${val%\"}"       # strip surrounding "
      val="${val#\'}"; val="${val%\'}"       # strip surrounding '
      export "APPTAINERENV_${key}=$val"
    done < "$AGENT_SECRETS_DIR/provider.env"
  fi
fi

# --- Claude credentials: existence gate (no longer a separate bind) ---
#
# Pre-Sprint-1, the wrapper had no HOME bind-mount and overlaid only a
# per-session read-only copy of ~/.claude/.credentials.json at
# /home/agentuser/.claude/.credentials.json:ro. Sprint 1 Task 1.7 +
# 1.5 now bind the whole ~/.claude/ writable (see AGENT_HOME_BINDS
# below for AGENT_NAME=claude), which subsumes that single-file
# overlay AND lets Claude refresh its OAuth token live (the previous
# :ro overlay broke token refresh). The TMP_CREDS_DIR scaffolding
# is kept for any future per-session overlay needs (e.g. if we want
# to layer a fresh-each-run credentials view back on top); for now
# it's just a no-op tmp dir with a cleanup trap.
TMP_CREDS_DIR=$(mktemp -d -p "$TMPDIR" agentcreds.XXXXXXXX)
trap 'rm -rf "$TMP_CREDS_DIR"' EXIT
CREDS_BINDS=()
if [ "$AGENT_NAME" = "claude" ] && [ ! -r "$HOME/.claude/.credentials.json" ]; then
  echo "agent-claude: ~/.claude/.credentials.json not found — run 'claude login' on submit node first." >&2
  exit 4
fi

# --- Bind secrets dir read-only into sandbox (in case agents read raw files) ---
SECRETS_BINDS=()
if [ -n "${AGENT_SECRETS_DIR:-}" ] && [ -d "$AGENT_SECRETS_DIR" ]; then
  SECRETS_BINDS=( --bind "$AGENT_SECRETS_DIR:/run/agent/secrets:ro" )
fi

# --- Per-agent HOME bind-mounts (synthesis §3.8/§3.10/§3.12; user decisions 2026-04-27) ---
#
# All four agents persist runtime state under $HOME ("agent state" =
# settings, deny-rules, OAuth tokens, session DBs, MCP config, memory,
# file-history, snapshots, LSP caches, prompt history, …). The base
# wrapper uses --no-mount home,tmp so the host HOME is invisible inside
# the SIF; without an explicit bind-mount each agent runs in "minimal"
# mode — its host-side state is unreachable.
#
# Strategy: per-agent, bind only the specific subdirs the agent needs,
# writable. The rest of $HOME stays isolated (defence-in-depth: deny
# rules cover ~/.ssh, ~/.aws, etc., and the cwd-bind keeps the agent
# away from anything not explicitly bound).
#
# Inside the SIF, $HOME is normally /home/agentuser/. We pass
# APPTAINERENV_HOME so the in-container HOME matches the host path —
# that way `~/.<agent>` inside the SIF resolves to the same location
# the user already uses on the host. If $HOME is missing pieces (just
# the bound subdir is present), Apptainer's tmpfs overlay creates
# empty parent dirs as needed.
#
# TODO (optional, post-MVP): relocate all ~/.{claude,codex,pi,opencode}
# state into <install_dir>/state/<agent>/ via per-agent env vars
# (CLAUDE_CONFIG_DIR, CODEX_HOME / OPENAI_CODEX_HOME, the Pi
# PI_CODING_AGENT_DIR, OPENCODE_CONFIG_DIR + friends). Then a single
# bind of <install_dir>/state/ would cover all four agents, the host
# $HOME would never be touched by the SIF, and group/shared installs
# could optionally share state across users. Not done now because (a)
# it changes UX (running `claude` outside the wrapper would no longer
# see HPC sessions unless the env vars are also set in the user's
# shell rc), and (b) some agents only honour these env vars in recent
# versions — needs per-agent verification.
AGENT_HOME_BINDS=()
case "$AGENT_NAME" in
  claude)
    mkdir -p "$HOME/.claude"
    if [ -d "$HOME/.claude" ]; then
      # Bind the whole ~/.claude/ writable so settings.json (deny
      # rules), CLAUDE.md (memory), file-history/, backups/, rules/,
      # teams/, statusbar config all persist + are readable inside
      # the SIF. The per-session .credentials.json copy below
      # (CREDS_BINDS) overlays the bind with a read-only tmpfs entry
      # so a hostile agent can't rewrite the credentials file.
      AGENT_HOME_BINDS+=( --bind "$HOME/.claude:$HOME/.claude" )
      export APPTAINERENV_HOME="$HOME"
    else
      echo "agent-${AGENT_NAME}: failed to create ~/.claude for bind-mount." >&2
      exit 11
    fi
    ;;
  codex)
    mkdir -p "$HOME/.codex"
    if [ -d "$HOME/.codex" ]; then
      # Bind the whole ~/.codex/ writable so config.toml (the
      # sandbox_mode = "workspace-write" + [sandbox_workspace_write]
      # schema we emit at install time) is actually read by Codex
      # inside the SIF — without the bind it's invisible and the
      # agent runs unsandboxed-by-config (still cwd-confined by
      # Apptainer, but the per-agent policy is unread). Also covers
      # auth.json (OAuth-based providers) and sessions/.
      AGENT_HOME_BINDS+=( --bind "$HOME/.codex:$HOME/.codex" )
      export APPTAINERENV_HOME="$HOME"
    else
      echo "agent-${AGENT_NAME}: failed to create ~/.codex for bind-mount." >&2
      exit 11
    fi
    ;;
  pi)
    mkdir -p "$HOME/.pi/agent"
    if [ -d "$HOME/.pi/agent" ]; then
      AGENT_HOME_BINDS+=( --bind "$HOME/.pi/agent:$HOME/.pi/agent" )
      export APPTAINERENV_HOME="$HOME"
    else
      echo "agent-${AGENT_NAME}: failed to create ~/.pi/agent for bind-mount." >&2
      exit 11
    fi
    ;;
  opencode)
    OC_OK=true
    for sub in .config/opencode .local/share/opencode .cache/opencode .local/state/opencode; do
      mkdir -p "$HOME/$sub"
      if [ -d "$HOME/$sub" ]; then
        AGENT_HOME_BINDS+=( --bind "$HOME/$sub:$HOME/$sub" )
      else
        OC_OK=false
        echo "agent-${AGENT_NAME}: failed to create ~/$sub for bind-mount." >&2
      fi
    done
    if ! $OC_OK; then
      exit 11
    fi
    export APPTAINERENV_HOME="$HOME"
    # OpenCode ships with default plugins; in HPC mode we let the
    # user/lab inject their own via OPENCODE_CONFIG. Disabling the
    # defaults avoids surprise auto-fetches during SLURM jobs.
    export APPTAINERENV_OPENCODE_DISABLE_DEFAULT_PLUGINS=1
    ;;
esac

# --- OPENCODE_* env-var passthrough (synthesis §3.12 bonus, opencode §3 URGENT 6) ---
# OpenCode reads a stack of OPENCODE_* environment variables for config,
# permissions, model picks, LSP toggles, etc. None were in the wrapper's
# allowlist; passing them through gives users a way to override SIF-side
# behaviour at invocation time without editing config files. Same
# poisoning-resistance regex applies to keys we forward.
if [ "$AGENT_NAME" = "opencode" ]; then
  for oc_var in \
      OPENCODE_CONFIG OPENCODE_CONFIG_DIR OPENCODE_CONFIG_CONTENT \
      OPENCODE_PERMISSION OPENCODE_DISABLE_PROJECT_CONFIG \
      OPENCODE_MODELS_URL OPENCODE_DISABLE_LSP_DOWNLOAD \
      OPENCODE_DB OPENCODE_TEST_HOME OPENCODE_AUTH_CONTENT; do
    if [ -n "${!oc_var:-}" ]; then
      # _is_valid_env_name and _is_poisonous_env_name are defined above.
      if _is_valid_env_name "$oc_var" && ! _is_poisonous_env_name "$oc_var"; then
        export "APPTAINERENV_${oc_var}=${!oc_var}"
      fi
    fi
  done
fi

# --- Audit log append (security §3.1 + §3.4) ---
# Synthesis §3.1: every interpolated value goes through jq's `--arg` /
# `--argjson` so escaping is uniform. The previous printf-based path
# was forgeable via $PWD containing `"` (now refused at the §3.1
# precondition above, but we belt-and-braces here too).
#
# Synthesis §3.4: line-atomic via flock(1). POSIX guarantees O_APPEND
# atomicity only for buffers ≤ PIPE_BUF (4 KB on Linux). Codex
# prompt-as-argv flows trivially exceed 4 KB; two concurrent agents
# in the same allocation could interleave bytes mid-line, producing
# unparseable JSONL. flock makes the append serialised at file scope.
if [ -n "${AGENT_LOGS_DIR:-}" ] && [ -w "$AGENT_LOGS_DIR" ]; then
  TODAY=$(date -u +%Y-%m-%d)
  TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  SIF_SHA=$(<"${SIF_RESOLVED}.sha256" 2>/dev/null || echo unknown)
  # Encode argv as a JSON array via jq --args so each element is
  # individually escaped; no risk of newlines or control characters
  # corrupting the line.
  ARGV_JSON=$(jq -nc --args '$ARGS.positional' -- "$@")
  AUDIT_LINE=$(jq -nc \
    --arg ts        "$TS" \
    --arg agent     "$AGENT_NAME" \
    --arg cwd       "$PWD" \
    --arg slurm_job_id "$SLURM_JOB_ID" \
    --arg sif_sha   "$SIF_SHA" \
    --argjson argv  "$ARGV_JSON" \
    '{ts: $ts, agent: $agent, cwd: $cwd, slurm_job_id: $slurm_job_id, sif_sha: $sif_sha, argv: $argv}')
  AUDIT_FILE="$AGENT_LOGS_DIR/${AGENT_NAME}-${TODAY}.jsonl"
  # flock the file descriptor used for the append so concurrent writers
  # serialise. fd 9 is opened on the audit file, the subshell holds the
  # lock for the duration of the printf, then releases it at exit.
  ( flock 9; printf '%s\n' "$AUDIT_LINE" >&9 ) 9>>"$AUDIT_FILE" \
    || echo "agent-${AGENT_NAME}: warning: failed to append audit log to $AGENT_LOGS_DIR" >&2
fi

# --- Pi first-run defaults (no-wrap-via-sif plan, phase 2b) ---
# Pi extensions are baked into the SIF at build time; the user's
# ~/.pi/agent/settings.json must reference them by `npm:` source. On a
# fresh user (no settings file yet) we copy the SIF-baked default
# settings into ~/.pi/agent/ so the four lab default extensions
# (pi-ask-user, pi-subagents, pi-web-access, pi-mcp-adapter) are wired
# up on the very first message. Best-effort — never blocks the agent.
if [ "$AGENT_NAME" = "pi" ] && [ ! -f "$HOME/.pi/agent/settings.json" ]; then
  mkdir -p "$HOME/.pi/agent"
  apptainer exec \
    --containall \
    --bind "$HOME/.pi/agent:$HOME/.pi/agent:rw" \
    "$SIF_RESOLVED" \
    sh -c 'test -r /opt/pi-default-settings.json && cp /opt/pi-default-settings.json "$HOME/.pi/agent/settings.json"' \
    2>/dev/null || true
fi

# --- Exec ---
exec apptainer exec \
  --containall \
  --no-mount home,tmp \
  --writable-tmpfs \
  --bind "$PWD:$PWD" \
  --pwd "$PWD" \
  --no-privs \
  "${ENV_BINDS[@]}" \
  "${SECRETS_BINDS[@]}" \
  "${CREDS_BINDS[@]}" \
  "${AGENT_HOME_BINDS[@]}" \
  "$SIF_RESOLVED" \
  "$AGENT_BINARY" "$@"
