#!/usr/bin/env bash
# Generated by coding-agents installer for {{AGENT_DISPLAY_NAME}}.
# Apptainer cwd-only sandbox wrapper. MVP scope — see docs/v2-deferred.md.
set -euo pipefail
umask 077

AGENT_NAME="{{AGENT_KEY}}"
AGENT_BINARY="{{AGENT_BINARY}}"

# --- Precondition: SLURM job ---
if [ -z "${SLURM_JOB_ID:-}" ]; then
  echo "agent-${AGENT_NAME}: refusing to run on submit node (SLURM_JOB_ID unset)." >&2
  echo "  Try: srun --account=compgen --time=08:00:00 --mem=5G --gres=tmpspace:5G \\" >&2
  echo "       --cpus-per-task=2 --job-name=${AGENT_NAME}_managed_de_ridder_lab \\" >&2
  echo "       --export=PATH,VIRTUAL_ENV,CONDA_PREFIX,CONDA_DEFAULT_ENV,LD_LIBRARY_PATH \\" >&2
  echo "       --pty bash" >&2
  exit 3
fi

# --- Job-name convention: <agent>_managed_de_ridder_lab (best effort) ---
# Lab convention so anything started via this installer is identifiable
# in `squeue` / accounting. Rename idempotently if the user forgot the
# --job-name flag at srun/sbatch time. scontrol may not be allowed for
# every user — tolerate failure silently.
WANTED_JOB_NAME="${AGENT_NAME}_managed_de_ridder_lab"
if [ "${SLURM_JOB_NAME:-}" != "$WANTED_JOB_NAME" ]; then
  if command -v scontrol >/dev/null 2>&1; then
    scontrol update jobid="$SLURM_JOB_ID" jobname="$WANTED_JOB_NAME" >/dev/null 2>&1 || true
  fi
fi

# --- Precondition: SIF readable ---
SIF="${AGENT_SIF:-{{DEFAULT_SIF_PATH}}}"
SIF_RESOLVED=$(readlink -e "$SIF" 2>/dev/null || true)
if [ -z "$SIF_RESOLVED" ] || [ ! -r "$SIF_RESOLVED" ]; then
  echo "agent-${AGENT_NAME}: SIF unreadable at $SIF (resolved: ${SIF_RESOLVED:-<broken>})." >&2
  echo "  Ask lab admin to build and copy the SIF to /hpc/compgen/users/shared/agent/." >&2
  exit 5
fi

# --- Precondition: cwd writable ---
if [ ! -w "$PWD" ]; then
  echo "agent-${AGENT_NAME}: cwd not writable: $PWD" >&2
  exit 7
fi

# --- Precondition: $TMPDIR (SLURM tmpspace expected) ---
if [ -z "${TMPDIR:-}" ] || [ ! -d "$TMPDIR" ]; then
  echo "agent-${AGENT_NAME}: \$TMPDIR is unset or missing — request --gres=tmpspace:5G in your srun." >&2
  exit 8
fi

# --- Canonicalize HOME ---
# SLURM can strip HOME from the env on some configurations even when it's
# in --export; downstream code (~/.claude/.credentials.json check, the
# pyvenv.cfg allowlist that resolves $HOME paths) needs HOME to be set
# under `set -u`. Look it up from passwd if missing.
if [ -z "${HOME:-}" ]; then
  if command -v getent >/dev/null 2>&1; then
    HOME=$(getent passwd "${USER:-$(id -un)}" | cut -d: -f6)
  fi
  if [ -z "${HOME:-}" ]; then
    echo "agent-${AGENT_NAME}: cannot determine \$HOME — pass it via srun --export." >&2
    exit 9
  fi
  export HOME
fi

# --- conda/venv carrying ($:ro per security H4; pyvenv.cfg canonicalized per H3) ---
ENV_BINDS=()
if [ -n "${VIRTUAL_ENV:-}" ]; then
  export APPTAINERENV_VIRTUAL_ENV="$VIRTUAL_ENV"
  if [ -f "$VIRTUAL_ENV/pyvenv.cfg" ]; then
    VENV_HOME=$(awk -F' *= *' '/^home/{print $2; exit}' "$VIRTUAL_ENV/pyvenv.cfg")
    if [ -n "$VENV_HOME" ]; then
      VENV_HOME_REAL=$(realpath -e "$VENV_HOME" 2>/dev/null || true)
      if [ -n "$VENV_HOME_REAL" ] && [[ "$VENV_HOME_REAL" != "$PWD"* ]]; then
        # Allowlist for pyvenv.cfg `home =` paths. We bind these read-only
        # into the sandbox so Python inside the venv can find its own
        # toolchain. Covers system Python, RHEL EPEL, Bright Cluster
        # modules, uv-managed Pythons (default install path is under
        # ~/.local/share/uv/python/…), conda installs in HOME, and pyenv.
        case "$VENV_HOME_REAL" in
          /opt/python/*|/usr/*|/cm/shared/apps/python/*) ;;
          "$HOME"/.local/share/uv/python/*) ;;
          "$HOME"/.local/uv/*) ;;
          "$HOME"/miniconda3/*|"$HOME"/miniconda/*) ;;
          "$HOME"/anaconda3/*|"$HOME"/anaconda/*) ;;
          "$HOME"/.pyenv/versions/*) ;;
          *)
            if [ -n "${CONDA_PREFIX:-}" ] && [[ "$VENV_HOME_REAL" == "$CONDA_PREFIX"* ]]; then
              :
            else
              echo "agent-${AGENT_NAME}: pyvenv.cfg home '$VENV_HOME_REAL' not in allowlist; ignoring." >&2
              VENV_HOME_REAL=""
            fi ;;
        esac
        if [ -n "$VENV_HOME_REAL" ]; then
          ENV_BINDS+=( --bind "$VENV_HOME_REAL:$VENV_HOME_REAL:ro" )
        fi
      fi
    fi
  fi
  export APPTAINERENV_PREPEND_PATH="$VIRTUAL_ENV/bin"
fi
if [ -n "${CONDA_PREFIX:-}" ]; then
  export APPTAINERENV_CONDA_PREFIX="$CONDA_PREFIX"
  export APPTAINERENV_CONDA_DEFAULT_ENV="${CONDA_DEFAULT_ENV:-}"
  CONDA_BASE="${CONDA_PREFIX%/envs/*}"
  [ "$CONDA_BASE" = "$CONDA_PREFIX" ] && CONDA_BASE="$CONDA_PREFIX"
  CONDA_BASE_REAL=$(realpath -e "$CONDA_BASE" 2>/dev/null || true)
  if [ -n "$CONDA_BASE_REAL" ] && [[ "$CONDA_BASE_REAL" != "$PWD"* ]]; then
    ENV_BINDS+=( --bind "$CONDA_BASE_REAL:$CONDA_BASE_REAL:ro" )
  fi
  if [ -z "${VIRTUAL_ENV:-}" ]; then
    export APPTAINERENV_PREPEND_PATH="$CONDA_PREFIX/bin"
  fi
fi
[ -n "${LD_LIBRARY_PATH:-}" ] && export APPTAINERENV_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"

# --- Per-provider API key passthrough from $AGENT_SECRETS_DIR (security M5) ---
_export_key_if_present() {
  local var_name="$1" file_name="$2"
  if [ -r "$AGENT_SECRETS_DIR/$file_name" ]; then
    export "APPTAINERENV_${var_name}=$(<"$AGENT_SECRETS_DIR/$file_name")"
  fi
}
if [ -n "${AGENT_SECRETS_DIR:-}" ] && [ -d "$AGENT_SECRETS_DIR" ]; then
  _export_key_if_present ANTHROPIC_API_KEY anthropic_api_key
  _export_key_if_present OPENAI_API_KEY    openai_api_key
  _export_key_if_present GEMINI_API_KEY    gemini_api_key
fi

# --- Per-session credential copy (Claude only — others use API keys above) ---
TMP_CREDS_DIR=$(mktemp -d -p "$TMPDIR" agentcreds.XXXXXXXX)
trap 'rm -rf "$TMP_CREDS_DIR"' EXIT
CREDS_BINDS=()
if [ -r "$HOME/.claude/.credentials.json" ]; then
  install -m 0600 "$HOME/.claude/.credentials.json" "$TMP_CREDS_DIR/.credentials.json"
  CREDS_BINDS=( --bind "$TMP_CREDS_DIR/.credentials.json:/home/agentuser/.claude/.credentials.json:ro" )
elif [ "$AGENT_NAME" = "claude" ]; then
  echo "agent-claude: ~/.claude/.credentials.json not found — run 'claude login' on submit node first." >&2
  exit 4
fi

# --- Bind secrets dir read-only into sandbox (in case agents read raw files) ---
SECRETS_BINDS=()
if [ -n "${AGENT_SECRETS_DIR:-}" ] && [ -d "$AGENT_SECRETS_DIR" ]; then
  SECRETS_BINDS=( --bind "$AGENT_SECRETS_DIR:/run/agent/secrets:ro" )
fi

# --- Audit log append (best effort; sha256 read from sidecar cached at install) ---
if [ -n "${AGENT_LOGS_DIR:-}" ] && [ -w "$AGENT_LOGS_DIR" ]; then
  TODAY=$(date -u +%Y-%m-%d)
  TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  SIF_SHA=$(<"${SIF_RESOLVED}.sha256" 2>/dev/null || echo unknown)
  ARGV_JSON=$(printf '%s\n' "$@" | jq -Rs 'split("\n") | map(select(length>0))' 2>/dev/null \
              || printf '"<argv-elided: jq not in host PATH>"')
  printf '{"ts":"%s","agent":"%s","cwd":"%s","slurm_job_id":"%s","sif_sha":"%s","argv":%s}\n' \
    "$TS" "$AGENT_NAME" "$PWD" "$SLURM_JOB_ID" "$SIF_SHA" "$ARGV_JSON" \
    >> "$AGENT_LOGS_DIR/${AGENT_NAME}-${TODAY}.jsonl" 2>/dev/null \
    || echo "agent-${AGENT_NAME}: warning: failed to append audit log to $AGENT_LOGS_DIR" >&2
fi

# --- Exec ---
exec apptainer exec \
  --containall \
  --no-mount home,tmp \
  --writable-tmpfs \
  --bind "$PWD:$PWD" \
  --pwd "$PWD" \
  --no-privs \
  "${ENV_BINDS[@]}" \
  "${SECRETS_BINDS[@]}" \
  "${CREDS_BINDS[@]}" \
  "$SIF_RESOLVED" \
  "$AGENT_BINARY" "$@"
