#!/usr/bin/env bash
# Generated by coding-agents installer for {{AGENT_DISPLAY_NAME}}.
# Apptainer cwd-only sandbox wrapper. MVP scope — see docs/v2-deferred.md.
set -euo pipefail
umask 077

AGENT_NAME="{{AGENT_KEY}}"
AGENT_BINARY="{{AGENT_BINARY}}"

# --- Precondition: SLURM job ---
if [ -z "${SLURM_JOB_ID:-}" ]; then
  echo "agent-${AGENT_NAME}: refusing to run on submit node (SLURM_JOB_ID unset)." >&2
  echo "  Try: srun --account=compgen --time=08:00:00 --mem=5G --gres=tmpspace:5G \\" >&2
  echo "       --cpus-per-task=2 --job-name=${AGENT_NAME}_managed_de_ridder_lab \\" >&2
  echo "       --export=PATH,VIRTUAL_ENV,CONDA_PREFIX,CONDA_DEFAULT_ENV,LD_LIBRARY_PATH \\" >&2
  echo "       --pty bash" >&2
  exit 3
fi

# --- Job-name convention: <agent>_managed_de_ridder_lab (best effort) ---
# Lab convention so anything started via this installer is identifiable
# in `squeue` / accounting. Rename idempotently if the user forgot the
# --job-name flag at srun/sbatch time. scontrol may not be allowed for
# every user — tolerate failure silently.
WANTED_JOB_NAME="${AGENT_NAME}_managed_de_ridder_lab"
if [ "${SLURM_JOB_NAME:-}" != "$WANTED_JOB_NAME" ]; then
  if command -v scontrol >/dev/null 2>&1; then
    scontrol update jobid="$SLURM_JOB_ID" jobname="$WANTED_JOB_NAME" >/dev/null 2>&1 || true
  fi
fi

# --- Precondition: SIF readable ---
SIF="${AGENT_SIF:-{{DEFAULT_SIF_PATH}}}"
SIF_RESOLVED=$(readlink -e "$SIF" 2>/dev/null || true)
if [ -z "$SIF_RESOLVED" ] || [ ! -r "$SIF_RESOLVED" ]; then
  echo "agent-${AGENT_NAME}: SIF unreadable at $SIF (resolved: ${SIF_RESOLVED:-<broken>})." >&2
  echo "  Ask lab admin to build and copy the SIF to /hpc/compgen/users/shared/agent/." >&2
  exit 5
fi

# --- Precondition: cwd writable ---
if [ ! -w "$PWD" ]; then
  echo "agent-${AGENT_NAME}: cwd not writable: $PWD" >&2
  exit 7
fi

# --- Precondition: $TMPDIR (SLURM tmpspace expected) ---
if [ -z "${TMPDIR:-}" ] || [ ! -d "$TMPDIR" ]; then
  echo "agent-${AGENT_NAME}: \$TMPDIR is unset or missing — request --gres=tmpspace:5G in your srun." >&2
  exit 8
fi

# --- Canonicalize HOME ---
# SLURM can strip HOME from the env on some configurations even when it's
# in --export; downstream code (~/.claude/.credentials.json check, the
# pyvenv.cfg allowlist that resolves $HOME paths) needs HOME to be set
# under `set -u`. Look it up from passwd if missing.
if [ -z "${HOME:-}" ]; then
  if command -v getent >/dev/null 2>&1; then
    HOME=$(getent passwd "${USER:-$(id -un)}" | cut -d: -f6)
  fi
  if [ -z "${HOME:-}" ]; then
    echo "agent-${AGENT_NAME}: cannot determine \$HOME — pass it via srun --export." >&2
    exit 9
  fi
  export HOME
fi

# --- conda/venv carrying ($:ro per security H4; pyvenv.cfg canonicalized per H3) ---
ENV_BINDS=()
if [ -n "${VIRTUAL_ENV:-}" ]; then
  export APPTAINERENV_VIRTUAL_ENV="$VIRTUAL_ENV"
  if [ -f "$VIRTUAL_ENV/pyvenv.cfg" ]; then
    VENV_HOME=$(awk -F' *= *' '/^home/{print $2; exit}' "$VIRTUAL_ENV/pyvenv.cfg")
    if [ -n "$VENV_HOME" ]; then
      VENV_HOME_REAL=$(realpath -e "$VENV_HOME" 2>/dev/null || true)
      if [ -n "$VENV_HOME_REAL" ] && [[ "$VENV_HOME_REAL" != "$PWD"* ]]; then
        # Allowlist for pyvenv.cfg `home =` paths. We bind these read-only
        # into the sandbox so Python inside the venv can find its own
        # toolchain. Covers system Python, RHEL EPEL, Bright Cluster
        # modules, uv-managed Pythons (default install path is under
        # ~/.local/share/uv/python/…), conda installs in HOME, and pyenv.
        case "$VENV_HOME_REAL" in
          /opt/python/*|/usr/*|/cm/shared/apps/python/*) ;;
          "$HOME"/.local/share/uv/python/*) ;;
          "$HOME"/.local/uv/*) ;;
          "$HOME"/miniconda3/*|"$HOME"/miniconda/*) ;;
          "$HOME"/anaconda3/*|"$HOME"/anaconda/*) ;;
          "$HOME"/.pyenv/versions/*) ;;
          *)
            if [ -n "${CONDA_PREFIX:-}" ] && [[ "$VENV_HOME_REAL" == "$CONDA_PREFIX"* ]]; then
              :
            else
              echo "agent-${AGENT_NAME}: pyvenv.cfg home '$VENV_HOME_REAL' not in allowlist; ignoring." >&2
              VENV_HOME_REAL=""
            fi ;;
        esac
        if [ -n "$VENV_HOME_REAL" ]; then
          ENV_BINDS+=( --bind "$VENV_HOME_REAL:$VENV_HOME_REAL:ro" )
        fi
      fi
    fi
  fi
  export APPTAINERENV_PREPEND_PATH="$VIRTUAL_ENV/bin"
fi
if [ -n "${CONDA_PREFIX:-}" ]; then
  export APPTAINERENV_CONDA_PREFIX="$CONDA_PREFIX"
  export APPTAINERENV_CONDA_DEFAULT_ENV="${CONDA_DEFAULT_ENV:-}"
  CONDA_BASE="${CONDA_PREFIX%/envs/*}"
  [ "$CONDA_BASE" = "$CONDA_PREFIX" ] && CONDA_BASE="$CONDA_PREFIX"
  CONDA_BASE_REAL=$(realpath -e "$CONDA_BASE" 2>/dev/null || true)
  if [ -n "$CONDA_BASE_REAL" ] && [[ "$CONDA_BASE_REAL" != "$PWD"* ]]; then
    ENV_BINDS+=( --bind "$CONDA_BASE_REAL:$CONDA_BASE_REAL:ro" )
  fi
  if [ -z "${VIRTUAL_ENV:-}" ]; then
    export APPTAINERENV_PREPEND_PATH="$CONDA_PREFIX/bin"
  fi
fi
[ -n "${LD_LIBRARY_PATH:-}" ] && export APPTAINERENV_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"

# --- Per-provider API key passthrough from $AGENT_SECRETS_DIR (security M5) ---
#
# Two mechanisms, both load into the sandbox via apptainer's APPTAINERENV_*
# convention:
#
# 1. Single-value credential files — one secret per file. The file's name
#    (uppercased) becomes the env var name. We look for these patterns:
#       *_api_key         → <NAME>_API_KEY        (most providers)
#       *_token           → <NAME>_TOKEN          (HF, GitHub, Anthropic OAuth)
#       *_endpoint        → <NAME>_ENDPOINT       (Azure OpenAI, etc.)
#       *_base_url        → <NAME>_BASE_URL       (Azure OpenAI base URL)
#       *_project         → <NAME>_PROJECT        (GCP)
#       *_location        → <NAME>_LOCATION       (GCP region)
#       *_resource_name   → <NAME>_RESOURCE_NAME  (Azure)
#
#    Drop the file in $AGENT_SECRETS_DIR with mode 0600. Examples:
#       openrouter_api_key, anthropic_api_key, openai_api_key,
#       gemini_api_key, groq_api_key, deepseek_api_key, mistral_api_key,
#       xai_api_key, cohere_api_key, fireworks_api_key, perplexity_api_key,
#       cerebras_api_key, opencode_api_key, kimi_api_key, zai_api_key,
#       minimax_api_key, ai_gateway_api_key, copilot_github_token,
#       gh_token, github_token, hf_token, anthropic_oauth_token,
#       azure_openai_api_key, azure_openai_endpoint, azure_openai_base_url,
#       google_cloud_api_key
#
# 2. provider.env — KEY=VALUE pairs, one per line, # for comments. Use
#    this for multi-variable configs that don't fit the patterns above
#    (Azure resource names, GCP project IDs, custom base URLs, …).
#       AZURE_OPENAI_RESOURCE_NAME=mycompany-openai
#       GOOGLE_CLOUD_PROJECT=my-project-123
#       GOOGLE_CLOUD_LOCATION=us-central1
if [ -n "${AGENT_SECRETS_DIR:-}" ] && [ -d "$AGENT_SECRETS_DIR" ]; then
  shopt -s nullglob
  for keyfile in \
      "$AGENT_SECRETS_DIR"/*_api_key \
      "$AGENT_SECRETS_DIR"/*_token \
      "$AGENT_SECRETS_DIR"/*_endpoint \
      "$AGENT_SECRETS_DIR"/*_base_url \
      "$AGENT_SECRETS_DIR"/*_project \
      "$AGENT_SECRETS_DIR"/*_location \
      "$AGENT_SECRETS_DIR"/*_resource_name; do
    [ -r "$keyfile" ] || continue
    name=$(basename "$keyfile")
    var_name=$(echo "$name" | tr '[:lower:]-' '[:upper:]_')
    value=$(<"$keyfile")
    # Strip trailing newline so string-equality checks aren't tripped up.
    export "APPTAINERENV_${var_name}=${value%$'\n'}"
  done
  shopt -u nullglob

  if [ -r "$AGENT_SECRETS_DIR/provider.env" ]; then
    while IFS='=' read -r key val; do
      key="${key#"${key%%[![:space:]]*}"}"   # trim leading whitespace
      key="${key%"${key##*[![:space:]]}"}"   # trim trailing whitespace
      [ -z "$key" ] && continue
      case "$key" in \#*) continue ;; esac
      val="${val%$'\n'}"
      val="${val#\"}"; val="${val%\"}"       # strip surrounding "
      val="${val#\'}"; val="${val%\'}"       # strip surrounding '
      export "APPTAINERENV_${key}=$val"
    done < "$AGENT_SECRETS_DIR/provider.env"
  fi
fi

# --- Per-session credential copy (Claude only — others use API keys above) ---
TMP_CREDS_DIR=$(mktemp -d -p "$TMPDIR" agentcreds.XXXXXXXX)
trap 'rm -rf "$TMP_CREDS_DIR"' EXIT
CREDS_BINDS=()
if [ -r "$HOME/.claude/.credentials.json" ]; then
  install -m 0600 "$HOME/.claude/.credentials.json" "$TMP_CREDS_DIR/.credentials.json"
  CREDS_BINDS=( --bind "$TMP_CREDS_DIR/.credentials.json:/home/agentuser/.claude/.credentials.json:ro" )
elif [ "$AGENT_NAME" = "claude" ]; then
  echo "agent-claude: ~/.claude/.credentials.json not found — run 'claude login' on submit node first." >&2
  exit 4
fi

# --- Bind secrets dir read-only into sandbox (in case agents read raw files) ---
SECRETS_BINDS=()
if [ -n "${AGENT_SECRETS_DIR:-}" ] && [ -d "$AGENT_SECRETS_DIR" ]; then
  SECRETS_BINDS=( --bind "$AGENT_SECRETS_DIR:/run/agent/secrets:ro" )
fi

# --- Audit log append (best effort; sha256 read from sidecar cached at install) ---
if [ -n "${AGENT_LOGS_DIR:-}" ] && [ -w "$AGENT_LOGS_DIR" ]; then
  TODAY=$(date -u +%Y-%m-%d)
  TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  SIF_SHA=$(<"${SIF_RESOLVED}.sha256" 2>/dev/null || echo unknown)
  ARGV_JSON=$(printf '%s\n' "$@" | jq -Rs 'split("\n") | map(select(length>0))' 2>/dev/null \
              || printf '"<argv-elided: jq not in host PATH>"')
  printf '{"ts":"%s","agent":"%s","cwd":"%s","slurm_job_id":"%s","sif_sha":"%s","argv":%s}\n' \
    "$TS" "$AGENT_NAME" "$PWD" "$SLURM_JOB_ID" "$SIF_SHA" "$ARGV_JSON" \
    >> "$AGENT_LOGS_DIR/${AGENT_NAME}-${TODAY}.jsonl" 2>/dev/null \
    || echo "agent-${AGENT_NAME}: warning: failed to append audit log to $AGENT_LOGS_DIR" >&2
fi

# --- Exec ---
exec apptainer exec \
  --containall \
  --no-mount home,tmp \
  --writable-tmpfs \
  --bind "$PWD:$PWD" \
  --pwd "$PWD" \
  --no-privs \
  "${ENV_BINDS[@]}" \
  "${SECRETS_BINDS[@]}" \
  "${CREDS_BINDS[@]}" \
  "$SIF_RESOLVED" \
  "$AGENT_BINARY" "$@"
